name: ci pipeline

on:
  push:
    branches:
      - main

jobs:
  feature-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # setup the repository in the runner
      - name: Setup Node.js # setup Node.js in the runner
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run test

      # - name: Upload coverage to Codecov
      # uses: codecov/codecov-action@v1
      # with:
      # token: ${{ secrets.CODECOV_TOKEN }} # not needed for public repo, included in case it goes private
